version: '3'
services:
  web_ahorcado:
    container_name: cn_ahorcado
    image: php:8.1-apache
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      #- ./ahorcado.php:/app/ahorcado.php
      - ./ahorcado.php:/var/www/html/ahorcado.php
